"""bootstrap

Revision ID: 093fd3c64faf
Revises: 
Create Date: 2025-07-19 17:35:12.736190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093fd3c64faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bootstrap_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vehicle_listings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_listings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.REAL(), nullable=True),
    sa.Column('manufacturer', sa.TEXT(), nullable=True),
    sa.Column('model', sa.TEXT(), nullable=True),
    sa.Column('condition', sa.TEXT(), nullable=True),
    sa.Column('cylinders', sa.TEXT(), nullable=True),
    sa.Column('fuel', sa.TEXT(), nullable=True),
    sa.Column('odometer', sa.REAL(), nullable=True),
    sa.Column('title_status', sa.TEXT(), nullable=True),
    sa.Column('transmission', sa.TEXT(), nullable=True),
    sa.Column('drive', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('paint_color', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True)
    )
    op.drop_table('bootstrap_table')
    # ### end Alembic commands ###
