"""add user_listings and restore vehicle_listings

Revision ID: 1c7543261c4b
Revises: 093fd3c64faf
Create Date: 2025-07-19 17:37:30.346440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7543261c4b'
down_revision = '093fd3c64faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_site', sa.Text(), nullable=True),
    sa.Column('make', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('trim', sa.Text(), nullable=True),
    sa.Column('price_cad', sa.Integer(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('missing_fields', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('deal_score', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('vehicle_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price_cad', sa.Integer(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bootstrap_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bootstrap_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vehicle_listings')
    op.drop_table('user_listings')
    # ### end Alembic commands ###
