"""rename price_cad to price

Revision ID: d0ace560b125
Revises: 1c7543261c4b
Create Date: 2025-07-19 19:32:15.401219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ace560b125'
down_revision = '1c7543261c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('price_cad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_cad', sa.INTEGER(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
