"""rename price_cad → price on user_listings

Revision ID: da33d014241f
Revises: d0ace560b125
Create Date: 2025-07-20 21:46:06.573498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da33d014241f'
down_revision = 'd0ace560b125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('price_cad')

    with op.batch_alter_table('vehicle_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cylinders', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fuel', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('drive', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paint_color', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_listings', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('paint_color')
        batch_op.drop_column('type')
        batch_op.drop_column('drive')
        batch_op.drop_column('transmission')
        batch_op.drop_column('title_status')
        batch_op.drop_column('fuel')
        batch_op.drop_column('cylinders')
        batch_op.drop_column('condition')

    with op.batch_alter_table('user_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_cad', sa.INTEGER(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
